log_inspector/urls.py
import django

if django.VERSION >= (2, 0):
    from django.urls import re_path
else:
    from django.conf.urls import url as re_path

from .views import LogEntriesView, LogFilesView, HomeView, StartLiveView, DownloadLogFileView

app_name = "log_inspector"

urlpatterns = [
    re_path(r"^$", HomeView.as_view(), name='home'),
    re_path(r'^log-files/$', LogFilesView.as_view(), name='log_files'),
    re_path(r'^log-entries/(?P<filename>[\w\.-]+)/$', LogEntriesView.as_view(), name='log_entries'),
    re_path(r'^start-live/(?P<filename>[\w\.-]+)/$', StartLiveView.as_view(), name='start_live'),
    re_path(r'^download/(?P<filename>[\w\.-]+)/$', DownloadLogFileView.as_view(), name='download'),
]

log_inspector/models.py
from django.db import models

# Create your models here.

log_inspector/views.py
import io
import os
import zipfile
from itertools import islice

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView as _TemplateView

from . import settings
from .utils import get_log_entries, get_log_file_names, filter_log_entries, is_valid_filename

HTMX_STOP_POLLING = 286


class TemplateView(_TemplateView):
    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(TemplateView, self).dispatch(*args, **kwargs)


class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['custom_title'] = settings.LOG_INSPECTOR_FILE_LIST_TITLE
        context['custom_style_file'] = settings.LOG_INSPECTOR_FILE_LIST_STYLES
        return render(request, 'log_inspector/home.html', context=context)


class LogFilesView(TemplateView):
    def get(self, request, *args, **kwargs):
        search = request.GET.get('search', '')

        filenames = get_log_file_names(settings.LOG_INSPECTOR_FILES_DIR, search)
        filenames.sort()

        context = {'filenames': filenames}
        return render(request, 'log_inspector/log_files.html', context=context)


class LogEntriesView(TemplateView):
    def get(self, request, filename, *args, **kwargs):
        if not is_valid_filename(filename):
            raise Http404

        search = request.GET.get('search', '')
        page = request.GET.get('page', 1)
        action = request.META.get('HTTP_X_ACTION')
        is_live_action = action == 'LIVE'

        log_entries = get_log_entries(filename)
        log_entries = filter_log_entries(log_entries, search)

        max_lines = settings.LOG_INSPECTOR_MAX_READ_LINES if not is_live_action else settings.LOG_INSPECTOR_PAGE_LENGTH
        paginator = Paginator(list(islice(log_entries, max_lines)), settings.LOG_INSPECTOR_PAGE_LENGTH)
        start_index = (int(page) - 1) * paginator.per_page

        try:
            log_entries = paginator.page(page)
        except PageNotAnInteger:
            log_entries = paginator.page(1)
        except EmptyPage:
            log_entries = paginator.page(paginator.num_pages)

        context = {'log_entries': log_entries, 'filename': filename, 'start_index': start_index, 'search': search}
        if is_live_action:
            return render(request, 'log_inspector/log_entries_data.html', context)

        return render(request, 'log_inspector/log_entries_table.html', context, status=HTMX_STOP_POLLING)


class StartLiveView(TemplateView):
    def get(self, request, filename, *args, **kwargs):
        context = {'filename': filename}
        return render(request, 'log_inspector/start_live.html', context=context)


class DownloadLogFileView(TemplateView):
    def get(self, request, filename, *args, **kwargs):
        if not is_valid_filename(filename):
            raise Http404

        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w') as zip_file:
            zip_file.write(os.path.join(settings.LOG_INSPECTOR_FILES_DIR, filename))

        basename, _ = os.path.splitext(filename)
        response = HttpResponse(content_type='application/zip')
        response['Content-Disposition'] = f'attachment; filename="{basename}.zip"'
        response.write(zip_buffer.getvalue())
        return response

log_inspector/templates/log_inspector/file_log_entry_list.html
{% load static i18n %}

<tbody id="log-entries-data" x-data="{ copiedValue: '' }">
{% if log_entries %}
    {% for log_entry in log_entries %}
        <tr class="hover:bg-gray-100">
            <td scope="row" class="border p-2">{{ forloop.counter }}</td>
            <td class="border p-2 relative break-words">
                <div class="flex items-center">
                    <div class="flex-grow min-w-0">
                        {{ log_entry }}
                    </div>
                    <div x-data="{ showMsg: false }">
                        <i @click="copyText($event); showMsg = true; setTimeout(() => showMsg = false, 2000)"
                           class="fa-solid fa-copy copy-icon p-2 focus:outline-none cursor-pointer">
                        </i>
                        <div x-show="showMsg" @click.away="showMsg = false"
                             class="message fixed bottom-3 right-3 z-20 max-w-sm overflow-hidden bg-green-100 border
                                    border-green-300 rounded p-3 flex items-center justify-center text-green-600"
                             style="position: fixed; bottom: 20px; right: 20px; display: none;">
                            {% trans 'Copied to Clipboard' %}
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    {% endfor %}

{% else %}
    <tr class="hover:bg-gray-100">
        <td class="border p-2" colspan="2">{% trans 'No entries!' %}</td>
    </tr>
{% endif %}

</tbody>

{% include 'log_inspector/pagination.html' %}

log_inspector/templates/log_inspector/home.html
{% extends 'admin/base_site.html' %}
{% load static i18n %}
{% block title %}{% trans 'Django Log Inspector' %} - {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs" x-data>
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        <a href="{% url 'log_inspector:home' %}">
            {% if custom_title %}
                {{ custom_title }}
            {% else %}
                {% trans 'Django Log Inspector' %}
            {% endif %}
        </a>
        <i class="fa-solid fa-sun float-right focus:outline-none cursor-pointer text-2xl"
           x-show="$store.darkMode.on"
           @click="$store.darkMode.toggle()">
        </i>
        <i class="fa-solid fa-moon float-right focus:outline-none cursor-pointer text-2xl"
           x-show="!$store.darkMode.on"
           @click="$store.darkMode.toggle()">
        </i>
    </div>
{% endblock %}

{% block dark-mode-vars %}
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'log_inspector/css/output.css' %}">

    {% if custom_style_file %}
        <link type="text/css" href="{{ custom_style_file }}" rel="stylesheet">
    {% endif %}
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <script src="{% static 'log_inspector/js/htmx.min.js' %}" defer></script>
    <script src="{% static 'log_inspector/js/alpinejs.min.js' %}" defer></script>
    <script src="https://kit.fontawesome.com/7773a61110.js" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
    <div class="loading-spinner" id="spinner">
        <div class="lds-roller">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div x-data="{ live: false, isFileSelected: false }" class="p-4 mx-auto">
        <div class="flex">
            <div class="flex-none w-9/12 bg-white shadow-md p-6 dark:bg-slate-800">
                <div class="mb-6">
                    <h1 id="log-entries-title"
                        class="text-3xl font-bold text-black dark:text-white">
                        {% trans 'Django Log Inspector' %}
                    </h1>
                </div>

                <div>
                    <button id="live-button"
                            class="bg-blue-500 text-white px-4 py-2 rounded dark:bg-blue-700"
                            hx-target="#log-entries-table"
                            hx-trigger="click"
                            hx-swap="outerHTML"
                            @click="live = !live"
                            x-show="!live && isFileSelected">
                        {% trans 'Live' %}
                    </button>
                    <button id="stop-button"
                            class="bg-red-500 text-white px-4 py-2 mx-1 rounded dark:bg-red-700"
                            hx-target="#log-entries-table"
                            hx-trigger="click"
                            hx-swap="outerHTML"
                            @click="live = !live"
                            x-show="live && isFileSelected">
                        {% trans 'Stop' %}
                    </button>
                    <button id="refresh-button"
                            class="bg-green-500 text-white px-4 py-2 mx-1 rounded dark:bg-green-700"
                            hx-target="#log-entries-table"
                            hx-trigger="click"
                            hx-swap="outerHTML"
                            x-show="!live && isFileSelected">
                        {% trans 'Refresh' %}
                    </button>
                    <a id="download-link">
                        <button id="download-button"
                                class="bg-yellow-500 text-white px-4 py-2 mx-1  rounded"
                                x-show="isFileSelected">
                            {% trans 'Download' %}
                        </button>
                    </a>
                    <input id="search-box"
                           class="py-2 px-4 mt-1 border-2 border-gray-300 rounded-md focus:outline-none
                            focus:border-blue-500 transition duration-300 box-border h-10 w-2/5 float-right
                            dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                           type="search"
                           name="search"
                           placeholder="{% trans 'Search...' %}"
                           hx-target="#log-entries-table"
                           hx-trigger="input changed delay:300ms, search"
                           hx-swap="outerHTML"
                           x-show="!live && isFileSelected">
                </div>

                <table id="log-entries-table"
                       class="mt-6 w-full border-collapse dark:bg-slate-800">
                    <thead>
                    <tr>
                        <th scope="col"
                            class="border p-2 dark:border-gray-700 dark:bg-slate-700 dark:text-white dark:border-gray-700">
                            {% trans 'No.' %}
                        </th>
                        <th scope="col"
                            class="border p-2 dark:border-gray-700 dark:bg-slate-700 dark:text-white dark:border-gray-700">
                            {% trans 'Log entries' %}
                        </th>
                    </tr>
                    </thead>

                    <tbody id="log-entries-data">
                    <tr>
                        <td colspan="2"
                            class="border p-2 hover:bg-gray-100 dark:hover:bg-gray-500 dark:bg-slate-700 dark:border-gray-700 dark:text-white">
                            {% trans 'No entries!' %}
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="flex-none w-3/12 ml-6 bg-white shadow-md p-6 dark:bg-slate-800">
                <h2 class="pl-1 pr-2 py-3 text-2xl font-bold text-black dark:text-white">
                    {% trans 'Log Files' %}
                </h2>
                <input class="w-full py-2 px-4 border-2 border-gray-300 rounded-md focus:outline-none
                              focus:border-blue-500 transition duration-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                       type="search"
                       name="search"
                       placeholder="{% trans 'Search...' %}"
                       hx-get="{% url 'log_inspector:log_files' %}"
                       hx-trigger="input changed delay:300ms, search"
                       hx-target="#log-files-data"
                       hx-swap="outerHTML">

                <table id="log-files-table"
                       class="w-full border-collapse mt-2 dark:bg-slate-800"
                       hx-get="{% url 'log_inspector:log_files' %}"
                       hx-trigger="load"
                       hx-target="#log-files-data"
                       hx-swap="outerHTML">
                    <tbody id="log-files-data">
                    <tr>
                        <td colspan="2"
                            class="p-2 hover:bg-gray-100 dark:hover:bg-gray-500 dark:bg-slate-700 dark:border-gray-100/50 dark:text-white">
                            {% trans 'No entries!' %}
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        const elements = document.querySelectorAll('.content');
        elements.forEach((element) => {
            element.classList.add('bg-white')
            element.classList.add('dark:bg-slate-800')
        })

        document.addEventListener('alpine:init', () => {
            Alpine.store('darkMode', {
                on: window.matchMedia('(prefers-color-scheme: dark)').matches,

                init() {
                    document.documentElement.classList.toggle('dark', this.on);
                },

                toggle() {
                    this.on = !this.on;
                    document.documentElement.classList.toggle('dark', this.on);
                }
            })
        })

        document.addEventListener('htmx:configRequest', function (event) {
            const spinner = document.getElementById('spinner');
            if (event.detail.headers['X-ACTION'] === 'LIVE') {
                spinner.style.display = 'none';
            } else {
                spinner.style.display = 'flex';
            }
        });

        document.addEventListener('htmx:afterRequest', function (event) {
            const spinner = document.getElementById('spinner');
            spinner.style.display = 'none';
        })

        function updateFileName(event) {
            const td = event.target;
            const fileName = td.textContent.trim();

            const liveButton = document.getElementById('live-button');
            const stopButton = document.getElementById('stop-button');
            const searchBox = document.getElementById('search-box');
            const refreshButton = document.getElementById('refresh-button');
            const downloadLink = document.getElementById('download-link');
            const logEntriesTitle = document.getElementById('log-entries-title')
            liveButton.setAttribute('hx-get', `/logs/start-live/${fileName}/`)
            stopButton.setAttribute('hx-get', `/logs/log-entries/${fileName}/`)
            refreshButton.setAttribute('hx-get', `/logs/log-entries/${fileName}/`)
            searchBox.setAttribute('hx-get', `/logs/log-entries/${fileName}/`)
            downloadLink.setAttribute('href', `/logs/download/${fileName}/`)
            logEntriesTitle.innerText = fileName

            htmx.process(document.body)
        }

        function copyText(event) {
            const logEntryDiv = event.target.parentNode.previousElementSibling
            const textToCopy = logEntryDiv.textContent.trim();

            navigator.clipboard.writeText(textToCopy);

            Alpine.store('copiedValue', textToCopy);
        }
    </script>
{% endblock %}

log_inspector/templates/log_inspector/log_entries.html
{% load static i18n %}

<tbody id="log-entries-data" x-data="{ copiedValue: '' }">
{% if log_entries %}
    {% for log_entry in log_entries %}
        <tr class="hover:bg-gray-100 dark:hover:bg-gray-500 dark:bg-slate-700 dark:text-white dark:border-gray-700">
            <td class="border p-2 dark:border-gray-700">{{ forloop.counter }}</td>
            <td class="border p-2 relative break-words dark:border-gray-700 dark:text-white">
                <div class="flex items-center">
                    <div class="flex-grow min-w-0">
                        <p class="log-entry-text">{{ log_entry }}</p>
                    </div>
                    <div x-data="{ showMsg: false }">
                        <i @click="copyText($event); showMsg = true; setTimeout(() => showMsg = false, 2000)"
                           class="fa-solid fa-copy copy-icon p-2 focus:outline-none cursor-pointer absolute top-0 right-0">
                        </i>
                        <div x-show="showMsg" @click.away="showMsg = false"
                             class="message fixed bottom-3 right-3 z-20 max-w-sm overflow-hidden bg-green-100 border
                                        border-green-300 rounded p-3 flex items-center justify-center text-green-600
                                        dark:bg-gray-700 dark:border-gray-600 dark:text-white fixed bottom-15 right-15">
                            {% trans 'Copied to Clipboard' %}
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    {% endfor %}

{% else %}
    <tr class="hover:bg-gray-100 dark:hover:bg-gray-700">
        <td class="border p-2 hover:bg-gray-100 dark:hover:bg-gray-500 dark:bg-slate-700 dark:border-gray-700 dark:text-white"
            colspan="2">
            {% trans 'No entries!' %}
        </td>
    </tr>
{% endif %}

</tbody>

<tfoot id="log-entries-footer" hx-swap-oob="true" class="dark:bg-slate-800">
{% include 'log_inspector/pagination.html' %}
</tfoot>

log_inspector/templates/log_inspector/log_entries_data.html
{% load i18n %}

<tbody id="log-entries-data" x-data="{ copiedValue: '' }">
{% if log_entries %}

    {% for log_entry in log_entries %}
        <tr class="hover:bg-gray-100 dark:hover:bg-gray-500 dark:bg-slate-700 dark:text-white">
            <td class="p-2 dark:border-b-gray-100/50 ">{{ start_index|add:forloop.counter }}</td>
            <td class="p-2 dark:border-b-gray-100/50 relative break-words dark:text-white">
                <div class="flex items-center">
                    <div class="flex-grow min-w-0 mr-8">
                        <p class="log-entry-text">{{ log_entry }}</p>
                    </div>
                    <div x-data="{ showMsg: false }">
                        <i @click="copyText($event); showMsg = true; setTimeout(() => showMsg = false, 2000)"
                           class="fa-solid fa-copy copy-icon p-2 focus:outline-none cursor-pointer absolute top-0 right-0">
                        </i>
                        <div x-show="showMsg" @click.away="showMsg = false"
                             class="message fixed bottom-3 right-3 z-20 max-w-sm overflow-hidden bg-green-100 border
                                    border-green-300 rounded p-3 flex items-center justify-center text-green-600
                                    dark:bg-gray-700 dark:border-gray-600 dark:text-white fixed bottom-15 right-15">
                            {% trans 'Copied to Clipboard' %}
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    {% endfor %}

{% else %}
    <tr class="hover:bg-gray-100 dark:hover:bg-gray-500">
        <td class="border p-2 hover:bg-gray-100 dark:hover:bg-gray-500 dark:bg-slate-700 dark:border-gray-700 dark:text-white"
            colspan="2">
            {% trans 'No entries!' %}
        </td>
    </tr>
{% endif %}

log_inspector/templates/log_inspector/log_entries_table.html
{% load static i18n %}

<table id="log-entries-table"
       class="mt-6 w-full border-collapse table-fixed dark:bg-slate-800">
    <thead>
    <tr>
        <th scope="col"
            class="border p-2 w-10 dark:border-gray-700 dark:bg-slate-700 dark:text-white">
            {% trans 'No.' %}
        </th>
        <th scope="col"
            class="border p-2 dark:border-gray-700 dark:bg-slate-700 dark:text-white">
            {% trans 'Log entries' %}
        </th>
    </tr>
    </thead>

    {% include 'log_inspector/log_entries_data.html' %}

    <tfoot id="log-entries-footer" class="dark:bg-slate-800">
    {% include 'log_inspector/pagination.html' %}
    </tfoot>
</table>

log_inspector/templates/log_inspector/log_file_list.html
{% load static i18n %}


<tbody id="log-files-data" class="w-full">
{% if filenames %}
    {% for filename in filenames %}
        <tr class="hover:bg-gray-100">
            <td class="w-full cursor-pointer break-all"
                hx-get="{% url 'log_inspector:log_entries' filename=filename %}"
                hx-trigger="click"
                hx-target="#log-entries-data"
                hx-swap="outerHTML"
                @click="updateFileName($event); isFileSelected = true">
                {{ filename }}
            </td>
        </tr>
    {% endfor %}

{% else %}
    <tr class="hover:bg-gray-100">
        <td class="w-full" colspan="2">{% trans 'No entries!' %}</td>
    </tr>
{% endif %}
</tbody>

log_inspector/templates/log_inspector/log_files.html
{% load static i18n %}


<tbody id="log-files-data" class="w-full dark:bg-slate-800">
{% if filenames %}
    {% for filename in filenames %}
        <tr class="hover:bg-gray-100 dark::bg-gray-500 dark:bg-slate-700 dark:text-white">
            <td class="w-full cursor-pointer break-all dark:text-white dark:border-gray-100/50"
                hx-get="{% url 'log_inspector:log_entries' filename=filename %}"
                hx-trigger="click"
                hx-target="#log-entries-table"
                hx-swap="outerHTML"
                @click="updateFileName($event); isFileSelected = true; live=false">
                {{ filename }}
            </td>
        </tr>
    {% endfor %}
{% else %}
    <tr class="hover:bg-gray-100 dark::bg-gray-500 dark:bg-slate-700 dark:text-white dark:border-gray-100/50">
        <td class="w-full cursor-pointer break-all dark:text-white"
            colspan="2">
            {% trans 'No entries!' %}
        </td>
    </tr>
{% endif %}
</tbody>

log_inspector/templates/log_inspector/pagination.html
{% load static i18n %}

<tr>
    <td colspan="2" class="dark:bg-slate-800 dark:border-gray-700 dark:text-white">
        <div class="flex items-center justify-center mt-4 dark:bg-slate-800">
            {% if log_entries.has_previous %}
                <span class="px-4 py-2 border border-gray-300 rounded-l cursor-pointer dark:border-gray-700"
                      hx-get="{% url 'log_inspector:log_entries' filename=filename %}?page={{ log_entries.previous_page_number }}{% if search %}&search={{ search }}{% endif %}"
                      hx-target="#log-entries-table"
                      hx-swap="outerHTML">
                {% trans 'Previous' %}
            </span>
            {% endif %}
            {% for page_num in log_entries.paginator.page_range %}
                {% if page_num == log_entries.number %}
                    <span class="px-4 py-2 bg-blue-500 text-white rounded-md dark:bg-slate-600 dark:text-white">
                    {{ page_num }}
                </span>
                {% elif page_num == 1 or page_num == log_entries.paginator.num_pages %}
                    <span class="px-4 py-2 border border-gray-300 rounded-md cursor-pointer dark:border-gray-700"
                          hx-get="{% url 'log_inspector:log_entries' filename=filename %}?page={{ page_num }}{% if search %}&search={{ search }}{% endif %}"
                          hx-target="#log-entries-table"
                          hx-swap="outerHTML">
                    {{ page_num }}
                </span>
                {% elif page_num > log_entries.number|add:'-3' and page_num < log_entries.number|add:'3' %}
                    <span class="px-4 py-2 border border-gray-300 rounded-md cursor-pointer dark:border-gray-700"
                          hx-get="{% url 'log_inspector:log_entries' filename=filename %}?page={{ page_num }}{% if search %}&search={{ search }}{% endif %}"
                          hx-target="#log-entries-table"
                          hx-swap="outerHTML">
                    {{ page_num }}
                </span>
                {% elif page_num == log_entries.number|add:'-3' or page_num == log_entries.number|add:'3' %}
                    <span class="px-4 py-2 dark:border-gray-700">...</span>
                {% endif %}
            {% endfor %}

            {% if log_entries.has_next %}
                <span class="px-4 py-2 border border-gray-300 rounded-r cursor-pointer dark:border-gray-700"
                      hx-get="{% url 'log_inspector:log_entries' filename=filename %}?page={{ log_entries.next_page_number }}{% if search %}&search={{ search }}{% endif %}"
                      hx-target="#log-entries-table"
                      hx-swap="outerHTML">
                {% trans 'Next' %}
            </span>
            {% endif %}
        </div>
    </td>
</tr>

log_inspector/templates/log_inspector/start_live.html
{% load static i18n %}

<table id="log-entries-table"
       class="mt-6 w-full border-collapse table-fixed dark:bg-slate-800"
       hx-get="{% url 'log_inspector:log_entries' filename=filename %}"
       hx-headers='{"X-ACTION": "LIVE"}'
       hx-trigger="load, every 1s"
       hx-target="#log-entries-data"
       hx-swap="outerHTML">
    <thead>
    <tr>
        <th scope="col"
            class="border p-2 w-10 dark:border-gray-700 dark:bg-slate-700 dark:text-white dark:border-gray-700">
            {% trans 'No.' %}
        </th>
        <th scope="col"
            class="border p-2 dark:border-gray-700 dark:bg-slate-700 dark:text-white dark:border-gray-700">
            {% trans 'Log entries' %}
        </th>
    </tr>
    </thead>
    <tbody id="log-entries-data">
    <tr>
        <td colspan="2"
            class="border p-2 hover:bg-gray-100 dark:hover:bg-gray-500 dark:bg-slate-700 dark:border-gray-700 dark:text-white">
            {% trans 'No entries!' %}
        </td>
    </tr>
    </tbody>
</table>